"""
Django settings for SchoolManagment project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2e$ak)n!&2ak1uxg%-m5kbu!h07x9&jgtqa@h%oel_$o_z0j#w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    'students.apps.StudentsConfig',
    'teachers.apps.TeachersConfig',
    'courses.apps.CoursesConfig',
    'profiles.apps.ProfilesConfig',
    'user',
    'emails',
    'home',
    'notifications',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_cleanup.apps.CleanupConfig", # هنا حيث تفضل ان تكون بعد التطبيفات التي تحتوي على Models
    "django_extensions",
]

UNFOLD = {
    "SITE_HEADER": "لوحة التحكم - الجامعة",
    "SITE_TITLE": "نظام إدارة الطلاب",
    "SITE_LOGO": "images/logo.png",
    "SITE_LOGO_WIDTH": 180,
    "SITE_ICON": None,
    "DASHBOARD": {
        "widgets": [
            {
                "type": "chart",
                "title": "إحصائيات الطلاب",
                "model": "app_name.Student",  
                "field": "gpa",
            },
            {
                "type": "table",
                "title": "آخر الطلاب",
                "model": "app_name.Student",
                "limit": 5,
                "fields": ["f_name", "l_name", "level", "gpa"],
            },
        ]
    }
}

UNFOLD.update({
    "THEME": {
        "primary": "green",
        "secondary": "gray",
        "accent": "yellow",
        "success": "emerald",
        "warning": "amber",
        "danger": "red",
        "info": "blue",
    },
    "DASHBOARD": ["students.dashboard.cards"]
})

UNFOLD.update({
    "NAVIGATION": [
        {
            "title": "Students",
            "items": [
                {"model": "students.Student"},
            ]
        },
        {
            "title": "Reports",
            "items": [
                {"model": "students.StudentReport"},
            ]
        },
    ]
})




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SchoolManagment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'SchoolManagment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME' : 'Lab4',
        'USER': 'postgres',
        'PASSWORD' : '2852002772002',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]

# مكان تجميع ملفات static بعد collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"
# Media Configurations

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

#  منع الحذف التلقائي للملفات
CLEANUP_KEEP_MEDIA_FILES = True  # القيمة الافتراضية False

# منع الحذف التلقائي لبعض الـ storages
CLEANUP_IGNORE_STORAGE = ['storagename']


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'engosamahsaeed@gmail.com'
EMAIL_HOST_PASSWORD = 'ogomklfbhkmqbywg'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
