# Generated by Django 5.2.5 on 2025-08-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='User', max_length=20)),
                ('l_name', models.CharField(default='User', max_length=20)),
                ('age', models.IntegerField()),
                ('level', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=4)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(default=True)),
                ('report', models.TextField()),
            ],
        ),
    ]
