# Generated by Django 5.2.4 on 2025-09-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_report',
            field=models.FileField(null=True, upload_to='files/%y/%m/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y/%m/'),
        ),
    ]
