# Generated by Django 5.2.4 on 2025-09-05 23:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_student'),
        ('students', '0003_student_file_report_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='❌ الاسم الاول يجب ان يبدأ بحرف Capital و يحتوي على أحرف فقط', regex='^[A-Z][a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(max_length=20),
        ),
    ]
