# Generated by Django 5.2.4 on 2025-09-08 21:59

import django.core.validators
import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_course_alter_student_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), students.validators.validate_image_mimetype]),
        ),
    ]
