# Generated by Django 5.2.4 on 2025-08-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=5, verbose_name='الجنس')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('status', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=5, verbose_name='منتظم')),
            ],
        ),
    ]
