# Generated by Django 5.2.4 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_file_report_student_image'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='teachers', to='students.student', verbose_name='الطلاب'),
        ),
    ]
