# Generated by Django 5.2.5 on 2025-08-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('stage', models.CharField(choices=[('first', 'الأولى'), ('second', 'الثانية'), ('third', 'الثالثة')], max_length=20, verbose_name='المرحلة')),
            ],
        ),
    ]
